site_name: Yayzi Docs
site_url: https://docs.yayzi.co.uk
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
  logo: assets/logo.png
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2018 - 2025 Yayzi Broadband
extra:
  generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
plugins:
  - search
repo_url: https://github.com/Yayzi-Broadband/Docs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences